# Generated by Django 3.0.5 on 2020-04-20 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labaapp', '0003_auto_20200420_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 20, 52, 17, 335958)),
        ),
    ]
