# Generated by Django 3.0.5 on 2020-04-20 20:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labaapp', '0007_auto_20200420_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 23, 29, 46, 775929)),
        ),
    ]
