# Generated by Django 3.0.5 on 2020-04-21 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labaapp', '0008_auto_20200420_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 14, 23, 31, 414307)),
        ),
    ]
