# Generated by Django 3.0.5 on 2020-04-21 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labaapp', '0010_auto_20200421_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 18, 47, 6, 347056)),
        ),
    ]
