# Generated by Django 3.0.5 on 2020-04-21 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labaapp', '0014_auto_20200421_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 20, 20, 50, 956306)),
        ),
    ]
