# Generated by Django 3.0.5 on 2020-04-21 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labaapp', '0015_auto_20200421_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 20, 29, 38, 722481)),
        ),
    ]
