# Generated by Django 3.0.5 on 2020-04-21 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labaapp', '0016_auto_20200421_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 21, 22, 5, 44, 593464)),
        ),
    ]
